version: "3.8"

services:
  database_mysql:
    container_name: mydb
    image: mariadb:10
    user: 0:0
    volumes:
      - ./config.cnf:/etc/mysql/conf.d/config.cnf
      - /usr/local/var/mysql:/var/lib/mysql
    environment:
      - MYSQL_HOST=localhost
      - MYSQL_PORT=3306
      - MYSQL_DATABASE=mydb
      - MYSQL_USER=myuser
      - MYSQL_PASSWORD=mypass
      - MYSQL_ROOT_HOST=root
      - MYSQL_ROOT_PASSWORD=root
    ports:
      - 3306:3306
    networks:
      - skynet

networks:
  skynet: